version: '3.8'

services:
  my-grpc-server:
    # build: .
    image: my-grpc-server:latest
    ports:
      - "8009:8009"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD", "sleep", "10"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: shashi
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /c/Users/shash/postgresmount:/var/lib/postgresql/data

# volumes:
#   postgres_data:
