version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: shashi
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - /c/Users/shash/postgresmount:/var/lib/postgresql/data

# volumes:
#   postgres_data:
