// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: timeseries.proto

package aggregator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimeAggregatorService_QueryData_FullMethodName = "/TimeAggregatorService/QueryData"
)

// TimeAggregatorServiceClient is the client API for TimeAggregatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for querying time-series data
type TimeAggregatorServiceClient interface {
	QueryData(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type timeAggregatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeAggregatorServiceClient(cc grpc.ClientConnInterface) TimeAggregatorServiceClient {
	return &timeAggregatorServiceClient{cc}
}

func (c *timeAggregatorServiceClient) QueryData(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TimeAggregatorService_QueryData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeAggregatorServiceServer is the server API for TimeAggregatorService service.
// All implementations must embed UnimplementedTimeAggregatorServiceServer
// for forward compatibility.
//
// Service definition for querying time-series data
type TimeAggregatorServiceServer interface {
	QueryData(context.Context, *QueryRequest) (*QueryResponse, error)
	mustEmbedUnimplementedTimeAggregatorServiceServer()
}

// UnimplementedTimeAggregatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimeAggregatorServiceServer struct{}

func (UnimplementedTimeAggregatorServiceServer) QueryData(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryData not implemented")
}
func (UnimplementedTimeAggregatorServiceServer) mustEmbedUnimplementedTimeAggregatorServiceServer() {}
func (UnimplementedTimeAggregatorServiceServer) testEmbeddedByValue()                               {}

// UnsafeTimeAggregatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeAggregatorServiceServer will
// result in compilation errors.
type UnsafeTimeAggregatorServiceServer interface {
	mustEmbedUnimplementedTimeAggregatorServiceServer()
}

func RegisterTimeAggregatorServiceServer(s grpc.ServiceRegistrar, srv TimeAggregatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedTimeAggregatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimeAggregatorService_ServiceDesc, srv)
}

func _TimeAggregatorService_QueryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeAggregatorServiceServer).QueryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimeAggregatorService_QueryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeAggregatorServiceServer).QueryData(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeAggregatorService_ServiceDesc is the grpc.ServiceDesc for TimeAggregatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeAggregatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TimeAggregatorService",
	HandlerType: (*TimeAggregatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryData",
			Handler:    _TimeAggregatorService_QueryData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timeseries.proto",
}
